spring:
  application:
    name: cardtransaction
  datasource:
    url: jdbc:h2:mem:cardtransaction
    driverClassName: org.h2.Driver
    username: root
    password: root
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html